# IPConnectTest模块 使用异步asyncore 测试ip&port的connect是否成功

```Python
import asyncore
import socket


class IPConnectTest(asyncore.dispatcher):
	# @param callback_success(sock_id, hostname, port)
	# @param callback_fail(sock_id, hostname, port, error_id)
	def __init__(self, hostname, port, callback_success, callback_fail):
		asyncore.dispatcher.__init__(self)
		self.create_socket(socket.AF_INET, socket.SOCK_STREAM)
		self.connect((hostname, port))
		self.hostname = hostname
		self.port = port
		self.callback_success = callback_success
		self.callback_fail = callback_fail

	def handle_connect(self):
		self.callback_success(self._fileno, self.hostname, self.port)
		self.close()

	def handle_close(self):
		self.callback_fail(self._fileno, self.hostname, self.port, self.socket.getsockopt(socket.SOL_SOCKET, socket.SO_ERROR))
		self.close()


if __name__ == '__main__':
	def callback_success(sock_id, hostname, port):
		print('success sock_id={0}, hostname={1}, port={2}'.format(sock_id, hostname, port))

	def callback_fail(sock_id, hostname, port, error_id):
		print('fail sock_id={0}, hostname={1}, port={2}, error_id={3}'.format(sock_id, hostname, port, error_id))

	print('Test for class Scan')
	IPConnectTest('www.google.com', 80, callback_success, callback_fail)
	IPConnectTest('www.baidu.com', 80, callback_success, callback_fail)
	IPConnectTest('8.8.8.8', 53, callback_success, callback_fail)
	asyncore.loop()
```

